# Generated by Django 5.1.6 on 2025-03-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور'),
        ),
    ]
