# Generated by Django 5.1.6 on 2025-03-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_code',
            field=models.CharField(max_length=10, verbose_name='کد فعال سازی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استان'),
        ),
    ]
