# Generated by Django 5.1.2 on 2024-10-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("price", models.IntegerField()),
                ("descript", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
