# Generated by Django 5.1.2 on 2024-11-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
