# Generated by Django 5.1.2 on 2024-11-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0002_productmodel_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
