# Generated by Django 5.1.2 on 2024-11-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0003_productmodel_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmodel",
            options={"verbose_name": "محصول", "verbose_name_plural": "محصولات"},
        ),
        migrations.AddField(
            model_name="productmodel",
            name="sim_count",
            field=models.IntegerField(
                choices=[("1", "1 SIM"), ("2", "2 SIM"), ("3", "3 SIM")],
                null=True,
                verbose_name="تعداد سیم کارت",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="created_at",
            field=models.DateTimeField(null=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="descript",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.IntegerField(verbose_name="قیمت"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="آدرس در مرورگر",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="title",
            field=models.CharField(max_length=300, verbose_name="عنوان"),
        ),
    ]
