# Generated by Django 5.1.2 on 2024-11-01 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_module",
            "0004_alter_productmodel_options_productmodel_sim_count_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="آدرس در مرورگر",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="sim_count",
            field=models.CharField(
                choices=[("1", "1 SIM"), ("2", "2 SIM"), ("3", "3 SIM")],
                max_length=20,
                null=True,
                verbose_name="تعداد سیم کارت",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_module.productcategory",
                verbose_name="دسته بندی",
            ),
        ),
    ]
