# Generated by Django 5.1.2 on 2024-11-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_module",
            "0005_productcategory_alter_productmodel_sim_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
    ]
