# Generated by Django 5.1.2 on 2024-11-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0006_alter_productcategory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_for", models.IntegerField(verbose_name="کد شناسایی")),
                ("year", models.CharField(max_length=150, verbose_name="سال تولید")),
                (
                    "made_in",
                    models.CharField(max_length=200, verbose_name="کشور سازنده"),
                ),
            ],
            options={
                "verbose_name": "اطلاعات محصول",
                "verbose_name_plural": "اطلاعات محصولات",
            },
        ),
        migrations.AddField(
            model_name="productmodel",
            name="inform",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_module.inform",
                verbose_name="اطلاعات محصول",
            ),
        ),
    ]
