# Generated by Django 5.1.2 on 2024-11-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0007_inform_productmodel_inform"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "url",
                    models.CharField(max_length=200, verbose_name="آدرس در مرورگر"),
                ),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برند ها",
            },
        ),
        migrations.AddField(
            model_name="productmodel",
            name="brand",
            field=models.ManyToManyField(
                to="product_module.productbrand", verbose_name="برند"
            ),
        ),
    ]
