# Generated by Django 5.1.2 on 2024-11-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0008_productbrand_productmodel_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="brand",
            field=models.ManyToManyField(
                to="product_module.productbrand", verbose_name="تگ"
            ),
        ),
    ]
