# Generated by Django 5.1.4 on 2025-01-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_alter_productmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='products', verbose_name='تصویر محصول'),
        ),
    ]
