# Generated by Django 5.1.4 on 2025-01-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_productmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sim_count',
            field=models.CharField(choices=[('0', '0 Cylinder'), ('3', '3 Cylinder'), ('4', '4 Cylinder'), ('6', '6 Cylinder'), ('8', '8 Cylinder'), ('10', '10 Cylinder'), ('12', '12 Cylinder'), ('16', '16 Cylinder')], max_length=20, null=True, verbose_name='تعداد سیلندر'),
        ),
    ]
