# Generated by Django 5.1.4 on 2025-01-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_alter_productmodel_sim_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='sim_count',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cylinder_count',
            field=models.CharField(choices=[('0', '0 Cylinder'), ('3', '3 Cylinders'), ('4', '4 Cylinders'), ('6', '6 Cylinders'), ('8', '8 Cylinders'), ('10', '10 Cylinders'), ('12', '12 Cylinders'), ('16', '16 Cylinders')], max_length=20, null=True, verbose_name='تعداد سیلندر'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='seat_count',
            field=models.CharField(choices=[('0', '0 Seats'), ('3', '3 Seats'), ('4', '4 Seats')], max_length=20, null=True, verbose_name='تعداد صندلی'),
        ),
    ]
