# Generated by Django 5.1.4 on 2025-01-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_remove_productmodel_sim_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='cylinder_count',
            field=models.CharField(choices=[('0', 'Cylinder 0'), ('3', '3 Cylinders'), ('4', '4 Cylinders'), ('6', '6 Cylinders'), ('8', '8 Cylinders'), ('10', '10 Cylinders'), ('12', '12 Cylinders'), ('16', '16 Cylinders')], max_length=20, null=True, verbose_name='تعداد سیلندر'),
        ),
    ]
