# Generated by Django 5.1.4 on 2025-01-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_alter_productmodel_cylinder_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='seat_count',
            field=models.CharField(choices=[('4', '4 Seats'), ('5', '5 Seats'), ('7', '7 Seats')], max_length=20, null=True, verbose_name='تعداد صندلی'),
        ),
    ]
