# Generated by Django 5.1.4 on 2025-01-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_alter_productmodel_seat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
