# Generated by Django 5.1.4 on 2025-01-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_alter_productmodel_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image2',
            field=models.ImageField(null=True, upload_to='products', verbose_name='تصویر محصول'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image3',
            field=models.ImageField(null=True, upload_to='products', verbose_name='تصویر محصول'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='mainimage',
            field=models.ImageField(null=True, upload_to='products', verbose_name='تصویر اصلی محصول'),
        ),
    ]
