# Generated by Django 5.1.4 on 2025-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_module",
            "0017_rename_image_productmodel_image1_productmodel_image2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
