# Generated by Django 5.1.4 on 2025-01-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0018_productcategory_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="category"),
        ),
    ]
