# Generated by Django 5.1.4 on 2025-01-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0019_productcategory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(upload_to="category"),
        ),
    ]
