# Generated by Django 5.1.5 on 2025-01-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0020_alter_productcategory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="products", verbose_name="تصویر محصول"
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="products", verbose_name="تصویر محصول"
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="products", verbose_name="تصویر محصول"
            ),
        ),
    ]
