# Generated by Django 5.1.5 on 2025-01-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_module",
            "0021_alter_productmodel_image1_alter_productmodel_image2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="count",
            field=models.IntegerField(null=True, verbose_name="تعداد"),
        ),
    ]
