# Generated by Django 5.1.5 on 2025-02-03 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0023_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="user",
        ),
        migrations.AddField(
            model_name="rating",
            name="ip",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="product_module.productmodel",
            ),
        ),
    ]
