# Generated by Django 5.1.5 on 2025-02-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0025_ratingmodel_delete_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingmodel",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
