# Generated by Django 5.1.4 on 2025-02-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0027_productcommentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcommentmodel',
            options={'verbose_name': 'کامنت محصول', 'verbose_name_plural': 'کامنت\u200cهای محصول'},
        ),
    ]
