# Generated by Django 5.1.4 on 2025-02-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0028_alter_productcommentmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentmodel',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='رتبه'),
        ),
    ]
