# Generated by Django 5.1.4 on 2025-02-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0029_productcommentmodel_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingModel',
        ),
    ]
