# Generated by Django 5.1.2 on 2025-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0030_delete_ratingmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(upload_to="category", verbose_name="تصویر"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
        ),
    ]
