# Generated by Django 5.1.2 on 2025-02-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0031_alter_productcategory_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="discount",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0.05", "5%"),
                    ("0.1", "10%"),
                    ("0.15", "15%"),
                    ("0.2", "20%"),
                    ("0.25", "25%"),
                    ("0.3", "30%"),
                    ("0.35", "35%"),
                    ("0.4", "40%"),
                    ("0.45", "45%"),
                    ("0.5", "50%"),
                    ("0.55", "55%"),
                    ("0.6", "60%"),
                    ("0.65", "65%"),
                    ("0.7", "70%"),
                    ("0.75", "75%"),
                    ("0.8", "80%"),
                    ("0.85", "85%"),
                    ("0.9", "90%"),
                    ("0.95", "95%"),
                ],
                max_length=20,
                null=True,
                verbose_name="تخفیف",
            ),
        ),
    ]
