# Generated by Django 5.1.6 on 2025-03-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0032_productmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='visited',
            field=models.IntegerField(default=0, verbose_name='بازدید'),
        ),
    ]
