# Generated by Django 5.1.6 on 2025-03-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0033_productmodel_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
    ]
