# Generated by Django 5.1.6 on 2025-03-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0034_alter_productmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد'),
        ),
    ]
