# Generated by Django 5.1.6 on 2025-03-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0035_alter_productmodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='added_to_cart_count',
            field=models.IntegerField(default=0, verbose_name='تعداد افزودن به سبد خرید'),
        ),
    ]
