# Generated by Django 5.1.6 on 2025-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0036_productmodel_added_to_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='short_descript',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات مختصر'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='descript',
            field=models.TextField(verbose_name='توضیحات مفصل'),
        ),
    ]
