# Generated by Django 5.1.6 on 2025-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0037_productmodel_short_descript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='short_descript',
            field=models.TextField(verbose_name='توضیحات مختصر'),
        ),
    ]
