# Generated by Django 4.2 on 2025-04-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0038_alter_productmodel_short_descript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='cylinder_count',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='seat_count',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='Additional_descript',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی (اختیاری)'),
        ),
    ]
