# Generated by Django 5.1.6 on 2025-03-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='تحویل شده'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='process',
            field=models.BooleanField(default=False, verbose_name='درحال پردازش'),
        ),
    ]
