# Generated by Django 5.1.6 on 2025-03-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0002_cartmodel_delivery_cartmodel_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdetailmodel',
            options={'verbose_name': 'جزئیات سبد خرید', 'verbose_name_plural': 'جزئیات سبدهای خرید'},
        ),
    ]
