# Generated by Django 5.1.6 on 2025-03-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0003_alter_cartdetailmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='province',
        ),
    ]
