# Generated by Django 5.1.6 on 2025-03-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0004_remove_cartmodel_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetailmodel',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ کل'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='تلفن'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='cartdetailmodel',
            name='count',
            field=models.IntegerField(verbose_name='تعداد'),
        ),
    ]
