# Generated by Django 5.1.6 on 2025-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0005_cartdetailmodel_price_cartmodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetailmodel',
            name='price',
            field=models.FloatField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='city',
            field=models.CharField(max_length=200, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='cost',
            field=models.IntegerField(verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='phone',
            field=models.IntegerField(verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='province',
            field=models.CharField(max_length=200, verbose_name='استان'),
        ),
    ]
