# Generated by Django 5.1.6 on 2025-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0006_alter_cartdetailmodel_price_alter_cartmodel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetailmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='province',
        ),
        migrations.AlterField(
            model_name='cartdetailmodel',
            name='count',
            field=models.IntegerField(),
        ),
    ]
