# Generated by Django 5.1.6 on 2025-03-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0008_buyermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyermodel',
            options={'verbose_name': 'پردختی', 'verbose_name_plural': 'پرداختی ها'},
        ),
        migrations.AddField(
            model_name='buyermodel',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart_module.cartmodel', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='buyermodel',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
