# Generated by Django 5.1.6 on 2025-03-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0009_alter_buyermodel_options_buyermodel_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyermodel',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
    ]
