# Generated by Django 5.1.6 on 2025-03-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_uploadavatarmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusmodel',
            name='email',
        ),
    ]
