# Generated by Django 5.1.4 on 2025-01-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog")),
                ("title", models.CharField(max_length=300)),
                ("text", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
            },
        ),
    ]
