# Generated by Django 5.1.4 on 2025-01-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
