# Generated by Django 5.1.5 on 2025-01-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_module", "0002_blogmodel_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
