# Generated by Django 5.1.5 on 2025-01-27 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_module", "0006_commentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog_module.commentmodel",
                verbose_name="والد",
            ),
        ),
    ]
