# Generated by Django 5.1.5 on 2025-01-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_module", "0007_commentmodel_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="is_publish",
            field=models.BooleanField(default=False, verbose_name="منتشر"),
        ),
    ]
