# Generated by Django 5.1.2 on 2025-02-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_module", "0008_alter_commentmodel_is_publish"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentmodel",
            options={
                "verbose_name": "کامنت مقاله",
                "verbose_name_plural": "کامنت های مقاله",
            },
        ),
    ]
