# Generated by Django 5.1.2 on 2025-02-12 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_module", "0009_alter_commentmodel_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="date",
            field=models.DateTimeField(null=True, verbose_name="تاریخ"),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="image",
            field=models.ImageField(upload_to="blog", verbose_name="تصویر"),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="منتشر"),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="text",
            field=models.TextField(verbose_name="متن"),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="title",
            field=models.CharField(max_length=300, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="user",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="commentmodel",
            name="create",
            field=models.DateTimeField(auto_now_add=True, verbose_name="ایجاد شده در"),
        ),
    ]
