# Generated by Django 5.1.6 on 2025-03-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0010_alter_blogmodel_date_alter_blogmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='visited',
            field=models.IntegerField(default=0, verbose_name='بازدید'),
        ),
    ]
