# Generated by Django 5.1.4 on 2025-01-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='social_facebook',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sitesettingmodel',
            name='social_linkedin',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sitesettingmodel',
            name='social_twitter',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
