# Generated by Django 5.1.4 on 2025-01-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0002_sitesettingmodel_social_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
