# Generated by Django 5.1.4 on 2025-01-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0003_slidermodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slidermodel",
            options={"verbose_name": "اسلایدر", "verbose_name_plural": "اسلایدر ها"},
        ),
    ]
