# Generated by Django 5.1.4 on 2025-01-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0004_alter_slidermodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="slidermodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
