# Generated by Django 5.1.2 on 2025-02-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0005_slidermodel_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="aboutus")),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "درباره ما",
                "verbose_name_plural": "درباره ما",
            },
        ),
    ]
