# Generated by Django 5.1.2 on 2025-02-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0006_aboutusmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutusmodel",
            old_name="image",
            new_name="image1",
        ),
        migrations.RenameField(
            model_name="aboutusmodel",
            old_name="text",
            new_name="text1",
        ),
        migrations.RenameField(
            model_name="aboutusmodel",
            old_name="title",
            new_name="title1",
        ),
        migrations.AddField(
            model_name="aboutusmodel",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="aboutus"),
        ),
        migrations.AddField(
            model_name="aboutusmodel",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="aboutus"),
        ),
        migrations.AddField(
            model_name="aboutusmodel",
            name="text2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutusmodel",
            name="text3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutusmodel",
            name="title2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="aboutusmodel",
            name="title3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
