# Generated by Django 5.1.2 on 2025-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0007_rename_image_aboutusmodel_image1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutusmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
