# Generated by Django 5.1.2 on 2025-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0008_alter_aboutusmodel_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutusmodel",
            name="image1",
            field=models.ImageField(upload_to="aboutus", verbose_name="تصویر1"),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="image2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="aboutus",
                verbose_name="تصویر2(اختیاری)",
            ),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="image3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="aboutus",
                verbose_name="تصویر3(اختیاری)",
            ),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="text1",
            field=models.TextField(verbose_name="متن1"),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="text2",
            field=models.TextField(blank=True, null=True, verbose_name="متن2(اختیاری)"),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="text3",
            field=models.TextField(blank=True, null=True, verbose_name="متن3(اختیاری)"),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="title1",
            field=models.CharField(max_length=100, verbose_name="عنوان1"),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="title2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="عنوان2(اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="title3",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="عنوان3(اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="about_us",
            field=models.TextField(verbose_name="درباره ما"),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="address",
            field=models.TextField(verbose_name="آدرس"),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="fax",
            field=models.CharField(max_length=50, verbose_name="فکس"),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="logo",
            field=models.ImageField(upload_to="logo", verbose_name="لوگو"),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="تلفن"),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="social_facebook",
            field=models.CharField(max_length=150, null=True, verbose_name="فیس بوک"),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="social_instagram",
            field=models.CharField(max_length=150, verbose_name="اینستاگرام"),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="social_linkedin",
            field=models.CharField(max_length=150, null=True, verbose_name="لینکدین"),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="social_twitter",
            field=models.CharField(max_length=150, null=True, verbose_name="توئیتر"),
        ),
        migrations.AlterField(
            model_name="slidermodel",
            name="image",
            field=models.ImageField(upload_to="sliders", verbose_name="تصویر"),
        ),
        migrations.AlterField(
            model_name="slidermodel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
        ),
        migrations.AlterField(
            model_name="slidermodel",
            name="link",
            field=models.URLField(verbose_name="لینک"),
        ),
        migrations.AlterField(
            model_name="slidermodel",
            name="price",
            field=models.CharField(max_length=20, verbose_name="قیمت"),
        ),
        migrations.AlterField(
            model_name="slidermodel",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان"),
        ),
    ]
