# Generated by Django 5.1.2 on 2025-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sitesetting_module",
            "0009_alter_aboutusmodel_image1_alter_aboutusmodel_image2_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettingmodel",
            name="social_facebook",
        ),
        migrations.RemoveField(
            model_name="sitesettingmodel",
            name="social_linkedin",
        ),
        migrations.AddField(
            model_name="sitesettingmodel",
            name="social_telegram",
            field=models.CharField(
                max_length=150, null=True, verbose_name="تلگرام(اختیاری)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettingmodel",
            name="social_youtube",
            field=models.CharField(
                max_length=150, null=True, verbose_name="یوتیوب(اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="social_instagram",
            field=models.CharField(max_length=150, verbose_name="اینستاگرام(اختیاری)"),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="social_twitter",
            field=models.CharField(
                max_length=150, null=True, verbose_name="توئیتر(اختیاری)"
            ),
        ),
    ]
