# Generated by Django 5.1.2 on 2025-02-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0010_remove_sitesettingmodel_social_facebook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="social_instagram",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="اینستاگرام(اختیاری)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="social_telegram",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="تلگرام(اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="social_twitter",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="توئیتر(اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="social_youtube",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="یوتیوب(اختیاری)"
            ),
        ),
    ]
