# Generated by Django 5.1.2 on 2025-02-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0012_alter_sitesettingmodel_social_instagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutusmodel",
            name="image2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="aboutus",
                verbose_name="تصویر2 (اختیاری)",
            ),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="image3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="aboutus",
                verbose_name="تصویر3 (اختیاری)",
            ),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="text2",
            field=models.TextField(
                blank=True, null=True, verbose_name="متن2 (اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="text3",
            field=models.TextField(
                blank=True, null=True, verbose_name="متن3 (اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="title2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="عنوان2 (اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="title3",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="عنوان3 (اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="آدرس (اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="ایمیل (اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="fax",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="فکس (اختیاری)"
            ),
        ),
    ]
