# Generated by Django 5.1.2 on 2025-02-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sitesetting_module",
            "0013_alter_aboutusmodel_image2_alter_aboutusmodel_image3_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettingmodel",
            name="about_us",
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="ایمیل"
            ),
        ),
    ]
