# Generated by Django 5.1.2 on 2025-02-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0014_remove_sitesettingmodel_about_us_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="ایمیل"),
        ),
    ]
