# Generated by Django 5.1.2 on 2025-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0015_alter_sitesettingmodel_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettingmodel",
            name="working_hours",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ساعت کاری"
            ),
        ),
    ]
