# Generated by Django 5.1.2 on 2025-02-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0016_sitesettingmodel_working_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettingmodel",
            name="working_end_day",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="آخرین روز کاری"
            ),
        ),
        migrations.AddField(
            model_name="sitesettingmodel",
            name="working_start_day",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="اولین روز کاری"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="working_hours",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ساعت کاری"
            ),
        ),
    ]
