# Generated by Django 5.1.2 on 2025-02-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0017_sitesettingmodel_working_end_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettingmodel",
            name="working_hours",
        ),
        migrations.AddField(
            model_name="sitesettingmodel",
            name="working_end_hours",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="ساعت پایان کار (اختیاری)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettingmodel",
            name="working_start_hours",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="ساعت شروع کار (اختیاری)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="working_end_day",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="آخرین روز کاری (اختیاری)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingmodel",
            name="working_start_day",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="اولین روز کاری (اختیاری)",
            ),
        ),
    ]
