# Generated by Django 5.1.2 on 2025-02-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting_module", "0018_remove_sitesettingmodel_working_hours_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettingmodel",
            old_name="working_end_hours",
            new_name="working_end_hour",
        ),
        migrations.RenameField(
            model_name="sitesettingmodel",
            old_name="working_start_hours",
            new_name="working_start_hour",
        ),
    ]
