# Generated by Django 5.1.6 on 2025-03-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0019_rename_working_end_hours_sitesettingmodel_working_end_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='نام فروشگاه'),
        ),
    ]
