# Generated by Django 5.1.6 on 2025-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0020_sitesettingmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettingmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام فروشگاه'),
        ),
    ]
