# Generated by Django 5.1.6 on 2025-03-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0035_alter_productmodel_count'),
        ('sitesetting_module', '0021_alter_sitesettingmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermodel',
            name='products',
            field=models.ManyToManyField(to='product_module.productmodel', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders', verbose_name='تصویر'),
        ),
    ]
