# Generated by Django 5.1.6 on 2025-03-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0022_slidermodel_products_alter_slidermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidermodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='title',
        ),
    ]
