# Generated by Django 5.1.6 on 2025-03-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0023_remove_slidermodel_image_remove_slidermodel_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=1000, verbose_name='سوال۱')),
                ('answer1', models.TextField(verbose_name='پاسخ۱')),
                ('question2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سوال۲ (اختیاری)')),
                ('answer2', models.TextField(blank=True, null=True, verbose_name='پاسخ۲ (اختیاری)')),
                ('question3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سوال۳ (اختیاری)')),
                ('answer3', models.TextField(blank=True, null=True, verbose_name='پاسخ۳ (اختیاری)')),
                ('question4', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سوال۴ (اختیاری)')),
                ('answer4', models.TextField(blank=True, null=True, verbose_name='پاسخ۴ (اختیاری)')),
                ('question5', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سوال۵ (اختیاری)')),
                ('answer5', models.TextField(blank=True, null=True, verbose_name='پاسخ۵ (اختیاری)')),
                ('question6', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سوال۶ (اختیاری)')),
                ('answer6', models.TextField(blank=True, null=True, verbose_name='پاسخ۶ (اختیاری)')),
                ('question7', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سوال۷ (اختیاری)')),
                ('answer7', models.TextField(blank=True, null=True, verbose_name='پاسخ۷ (اختیاری)')),
                ('question8', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سوال۸ (اختیاری)')),
                ('answer8', models.TextField(blank=True, null=True, verbose_name='پاسخ۸ (اختیاری)')),
                ('question9', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سوال۹ (اختیاری)')),
                ('answer9', models.TextField(blank=True, null=True, verbose_name='پاسخ۹ (اختیاری)')),
                ('question10', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سوال۱۰ (اختیاری)')),
                ('answer10', models.TextField(blank=True, null=True, verbose_name='پاسخ۱۰ (اختیاری)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
    ]
