# Generated by Django 5.1.6 on 2025-03-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0024_questionsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='send_cost',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='هزینه ارسال کالاها'),
        ),
    ]
