# Generated by Django 5.1.6 on 2025-03-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0025_sitesettingmodel_send_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettingmodel',
            name='send_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='هزینه ارسال کالاها'),
        ),
    ]
