# Generated by Django 5.1.6 on 2025-03-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0026_alter_sitesettingmodel_send_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_amount', models.CharField(blank=True, choices=[('0.05', '5%'), ('0.1', '10%'), ('0.15', '15%'), ('0.2', '20%'), ('0.25', '25%'), ('0.3', '30%'), ('0.35', '35%'), ('0.4', '40%'), ('0.45', '45%'), ('0.5', '50%'), ('0.55', '55%'), ('0.6', '60%'), ('0.65', '65%'), ('0.7', '70%'), ('0.75', '75%'), ('0.8', '80%'), ('0.85', '85%'), ('0.9', '90%'), ('0.95', '95%')], max_length=20, null=True, verbose_name='تخفیف')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
            ],
        ),
    ]
